apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "az-cli.fullname" . }}
{{- if .Values.workloadIdentity.enabled }}
  namespace: {{ .Values.namespace }}
{{- end }}
  labels:
    {{- include "az-cli.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaNum }}
  selector:
    matchLabels:
      {{- include "az-cli.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        {{- include "az-cli.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - command:
          - sleep
          - "10000"
        volumeMounts:
        - name: example-secret-volume
          mountPath: {{ .Values.csiDriver.mountPath }}
          readOnly: true
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      volumes:
        - name: example-secret-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "csi-secretproviderclass"
