{{- if .Values.csiDriver.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: csi-secretproviderclass
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.csiDriver.clientId }}
    keyvaultName: {{ .Values.csiDriver.keyVaultName }}
    objects:  |
      array:
        - |
          objectName: example-secret
          objectType: secret
    tenantId: {{ .Values.csiDriver.tenantId }}
{{- end }}