{{- if .Values.workloadIdentity.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
{{- end }}
